"""
Deterministic offline workflow for FREE-FORM passenger questions (typed or spoken). No model involved.

The reply is assembled from three things only:
  1. verbatim quotes of passages that BM25 actually retrieved with a score above a threshold,
  2. the real result of get_service_status (via MCP) when the question depends on the current situation,
  3. the real case id returned by prepare_support_case (via MCP) when a handoff rule matches.
When none of these applies, the reply says so (action "unsupported"), or asks for a missing detail
(action "clarify"). Every reply is labelled as templated. Nothing here is generated by a language model.

The rules are intentionally simple and readable: regexes and a score threshold. Their limits are measured
by Part D of eval/run_eval.py.
"""
from __future__ import annotations

import json
import re

from . import config
from .agent import needs_live_status
from .mcp_client import MCPBridge
from .rag import BM25Retriever, tokenize

LABEL_HE = ("תשובה תבניתית (מצב הדגמה ללא מודל): ציטוטים ממסמכי ההדגמה ותוצאות כלי MCP בלבד "
            "– לא נוצרה על ידי מודל שפה")

MIN_PASSAGE_SCORE = 6.0   # below this BM25 score a passage is not quoted (chosen from the score dump of the eval set: relevant hits scored 6+, noise below)
MAX_QUOTES = 2

# Handoff rules: first match wins. Only what the passenger wrote is put in the case.
HANDOFF_RULES: list[tuple[str, list[str]]] = [
    ("double_charge", [r"חיוב כפול", r"חויבתי פעמיים", r"חייבו אותי פעמיים", r"פעמיים"]),
    ("fine_appeal", [r"קנס", r"לערער", r"ערעור"]),
    ("payment_refund", [r"החזר", r"ביטול חיוב", r"ביטול החיוב", r"לבטל את החיוב"]),
    ("complaint", [r"תלונה", r"להתלונן", r"גס רוח", r"התנהגות"]),
    ("lost_item", [r"שכחתי", r"איבדתי", r"אבד לי", r"אבדה לי"]),
]
# Documents that are known to disagree (an old and a current version kept on purpose).
CONFLICT_GROUPS = [("refunds_v2", "refunds_v1_old")]
# A quoted passage that itself says the information is missing -> the honest action is "unsupported".
MISSING_MARKERS = ["אינו מציין", "אין פירוט", "אינו מגדיר", "לא מגדיר", "אינה מציינת"]
ELEVATOR_RE = re.compile(r"מעלית|מעליות|מדרגות נעות")
# Price questions are only answerable from a passage that actually states a price.
_W = r"(?<![א-ת])(?:%s)(?![א-ת])"   # Hebrew word boundary: "עלות" must not match inside "להעלות"
PRICE_QUESTION_RE = re.compile(_W % r"כמה עולה|כמה זה עולה|כמה משלמים|מה המחיר|מחיר|מחירים|עלות|תעריף|תעריפים")
PRICE_SOURCE_RE = re.compile(r"₪|\d+\s*(ש\"ח|שקל|שקלים)")
PRICE_TOPIC_RE = re.compile(r"תעריף|מחיר")
LONG_DIGITS_RE = re.compile(r"\d[\d \-]{11,}\d")   # 13+ digit runs: looks like a full card number


def _known_stations() -> list[str]:
    data = json.loads(config.STATUS_FILE.read_text(encoding="utf-8"))
    return data.get("known_stations", [])


def _find_station(question: str) -> str | None:
    # Longest match first so "פתח תקווה מרכז" wins over shorter names contained in it.
    for st in sorted(_known_stations(), key=len, reverse=True):
        if st in question:
            return st
    return None


def _handoff_category(question: str) -> str | None:
    for category, patterns in HANDOFF_RULES:
        if any(re.search(p, question) for p in patterns):
            return category
    return None


def _status_sentence(payload: dict) -> str:
    parts = [f"מצב השירות (נתוני הדגמה, נבדק כעת): {payload.get('summary_he', '')}".strip()]
    for d in payload.get("disruptions") or []:
        if d.get("alternative_he"):
            parts.append(d["alternative_he"])
    st = payload.get("station_query")
    if st and payload.get("station_known") is False:
        parts.append(f"התחנה \"{st}\" אינה מוכרת במערכת ההדגמה, ולכן אין לי מידע ספציפי עליה.")
    info = payload.get("station_info") or {}
    if info.get("note_he"):
        parts.append(f"תחנת {st}: {info['note_he']}")
    if info.get("in_disrupted_segment"):
        parts.append(f"תחנת {st} נמצאת בקטע המושבת.")
    return " ".join(parts)


async def run_free_question(question: str, history: list[dict], retriever: BM25Retriever, bridge: MCPBridge) -> dict:
    steps: list[dict] = []
    flags: list[str] = []
    original = question
    question = question.strip()

    # 0. Redact anything that looks like a full card number; never echo it.
    redacted = False
    if LONG_DIGITS_RE.search(question):
        question = LONG_DIGITS_RE.sub("[מספר הוסר]", question)
        redacted = True
        steps.append({"step": "redaction", "detail_he": "זוהה מספר ארוך שנראה כמספר כרטיס; הוסר לפני כל עיבוד."})

    tokens = tokenize(question)
    # 1. Very short questions: ask what it is about (use the previous turn for retrieval context if any).
    prev_user = next((m["content"] for m in reversed(history) if m["role"] == "user"), "")
    query = question if len(tokens) >= 4 or not prev_user else f"{prev_user} {question}"

    # 2. Real retrieval.
    hits = retriever.retrieve(query, k=config.TOP_K)
    retrieved = [dict(p.as_dict(), score=round(s, 2)) for p, s in hits]
    steps.append({"step": "retrieval", "detail_he": f"אחזור BM25 אמיתי: {len(retrieved)} פסקאות (סף לציטוט: ציון {MIN_PASSAGE_SCORE})."})
    # A passage is quotable only if it scores above the threshold AND matches the question in its own
    # section title or body (a match through the document title alone is not enough).
    q_tokens_exp = tokenize(query, expand_query=True)
    strong = [p for p in retrieved
              if p["score"] >= MIN_PASSAGE_SCORE and retriever.get(p["id"]).matches_in_own_text(q_tokens_exp)]
    # If some retrieved section is titled with a word from the question, that section is explicitly about the
    # topic: quote only such sections rather than higher-scoring sections that merely share generic words.
    title_hits = [p for p in strong if retriever.get(p["id"]).matches_section_title(q_tokens_exp)]
    if title_hits:
        strong = title_hits
        steps.append({"step": "section_title_match", "detail_he": "כותרת סעיף תואמת למילה מהשאלה; מצטטים רק סעיפים כאלה."})

    # Price questions: quotable only from a passage that states a price. The demo documents state none.
    price_question = bool(PRICE_QUESTION_RE.search(question))
    if price_question and not any(PRICE_SOURCE_RE.search(p["text"]) for p in strong):
        strong = [p for p in retrieved if PRICE_TOPIC_RE.search(p["text"])][:1]   # only a passage about tariffs, if any
        steps.append({"step": "price_rule", "detail_he": "שאלת מחיר: אף פסקה שאוחזרה אינה מכילה מחיר, ולכן התשובה מסומנת כלא נתמכת."})

    live = needs_live_status(question)
    station = _find_station(question)
    category = _handoff_category(question)
    log_start = len(bridge.call_log)

    # 3. Clarify rules (before any tool call). A question that is short, or that matches nothing in the
    #    documents, and carries no live/handoff/station signal cannot be routed honestly -> ask.
    top_score = retrieved[0]["score"] if retrieved else 0.0
    if (len(tokens) < 4 or top_score < 2.0) and not live and not category and not station:
        steps.append({"step": "clarify", "detail_he": "השאלה קצרה מדי לזיהוי נושא; מבקשים הבהרה במקום לנחש."})
        return _result(question, "clarify",
                       "כדי לעזור אני צריך עוד פרט אחד: על מה מדובר – תשלום או חיוב, שיבוש בשירות, או עזרה בתחנה? ובאיזו תחנה?",
                       [], retrieved, [], None, flags, steps)
    if live and ELEVATOR_RE.search(question) and not station:
        steps.append({"step": "clarify", "detail_he": "שאלה על מעלית ללא שם תחנה; מצב מעליות נבדק לפי תחנה."})
        return _result(question, "clarify", "באיזו תחנה מדובר? מצב המעליות נבדק לפי תחנה.", [], retrieved, [], None, flags, steps)

    # 4. Live status via the real MCP tool.
    status_text, status_error = "", False
    if live:
        args = {"station": station} if station else {}
        text, is_error = await bridge.call_tool("get_service_status", args)
        steps.append({"step": "mcp_call", "detail_he": f"קריאה אמיתית לכלי MCP get_service_status{'(' + station + ')' if station else ''} – {'שגיאה' if is_error else 'הצליחה'}."})
        if is_error:
            status_error = True
            status_text = ("לא הצלחתי לוודא את מצב השירות כרגע: מערכת מצב השירות (הדגמה) החזירה שגיאה. "
                           "מומלץ לבדוק בערוצים הרשמיים של המפעילה או לפנות לנציג.")
        else:
            try:
                status_text = _status_sentence(json.loads(text))
            except json.JSONDecodeError:
                status_error = True
                status_text = "מערכת מצב השירות החזירה תשובה לא קריאה; לא ניתן לוודא את המצב כרגע."

    # 5. Conflicting documents?
    conflict = False
    quotes: list[dict] = []
    for a, b in CONFLICT_GROUPS:
        pa = next((p for p in strong if p["doc_id"] == a), None)
        pb = next((p for p in strong if p["doc_id"] == b), None)
        if pa and pb:
            conflict = True
            quotes = [pa, pb]
            steps.append({"step": "conflict", "detail_he": f"שתי גרסאות סותרות אוחזרו ({a}, {b}); לא בוחרים אחת בשקט."})
    if not quotes:
        quotes = strong[:MAX_QUOTES]
    # Handoff questions: the escalation policy is the passage that justifies the handoff; cite it when retrieved.
    if category:
        anchor = next((p for p in retrieved if p["doc_id"] == "escalation_policy"), None)
        if anchor and anchor["id"] not in {q["id"] for q in quotes}:
            quotes = [anchor] + quotes[:MAX_QUOTES - 1]

    # 6. Handoff via the real MCP tool (only what the passenger said goes in).
    case = None
    if category or conflict:
        cat = category or "other"
        summary = f"שאלת הנוסע (כפי שנמסרה): {question}"
        if conflict:
            summary += " | נמצאו שתי גרסאות סותרות במסמכים; נדרש אימות של נציג."
        checks = f"אחזור מסמכים: {', '.join(p['id'] for p in quotes) or 'ללא פסקה מעל הסף'}"
        if live:
            checks += f"; מצב שירות: {'שגיאה' if status_error else 'נבדק'}"
        text, is_error = await bridge.call_tool("prepare_support_case", {
            "category": cat, "summary_he": summary,
            "passenger_details_he": "רק הפרטים שמופיעים בשאלה; לא נוספו פרטים.",
            "checks_done_he": checks,
        })
        steps.append({"step": "mcp_call", "detail_he": f"קריאה אמיתית לכלי MCP prepare_support_case ({cat}) – {'שגיאה' if is_error else 'הצליחה'}."})
        if not is_error:
            try:
                case = json.loads(text)
            except json.JSONDecodeError:
                case = {"raw": text}
        else:
            flags.append("mcp_case_error")

    # 7. Assemble the templated reply.
    parts: list[str] = []
    if redacted:
        parts.append("לתשומת לבך: הסרתי מספר ארוך שנראה כמספר כרטיס. אין למסור מספר כרטיס מלא; ארבע ספרות אחרונות מספיקות לבירור.")
    if status_text:
        parts.append(status_text)
    if conflict:
        parts.append("שימו לב: במסמכי ההדגמה נמצאו שתי גרסאות סותרות בנושא זה. שתיהן מצוטטות כאן, ונדרש אימות של נציג.")
    for p in quotes:
        parts.append(f"לפי מסמך ההדגמה \"{p['doc_title']}\" (סעיף \"{p['section_title']}\"): {' '.join(p['text'].split())}")
    if case:
        parts.append(f"הוכנה פנייה לנציג אנושי (הדגמה), מספר {case.get('case_id', '')}. הפנייה כוללת רק את מה שנמסר בשאלה; נציג יחזור אליך.")

    # "Information missing" rule: a quoted passage may contain a sentence saying the document does not
    # specify something. That only matters if the question is about that very thing, so we require at least
    # two content words of the question to appear in that sentence (e.g. "כמה זמן ... חפצים").
    missing = _question_hits_missing_sentence(question, quotes)
    if case:
        action = "handoff"
    elif price_question and not any(PRICE_SOURCE_RE.search(p["text"]) for p in quotes):
        action = "unsupported"
        parts.append("לא מצאתי במסמכי ההדגמה מידע על מחירים או תעריפים, ולכן אין לי תשובה על המחיר. "
                     "לבירור תעריפים והנחות יש לפנות למחשבון התעריפים של המפעילה או לנציג.")
    elif not quotes and not status_text:
        action = "unsupported"
        parts.append("לא מצאתי במסמכי ההדגמה פסקה שעונה על השאלה, ולא זוהתה שאלה על מצב השירות הנוכחי. "
                     "אפשר לנסח מחדש (למשל לציין תחנה או נושא), או לפנות לנציג שירות.")
    elif status_error and not quotes:
        action = "unsupported"
    elif missing and not status_text:
        action = "unsupported"
        parts.append("הפסקה שאוחזרה מציינת במפורש שהפרט שנשאל עליו אינו מוגדר במסמך, ולכן אין לי תשובה מבוססת; מומלץ לפנות לנציג.")
    else:
        action = "answer"
    steps.append({"step": "templated_response", "detail_he": LABEL_HE})
    tool_calls = bridge.call_log[log_start:]
    return _result(question, action, " ".join(parts), quotes, retrieved, tool_calls, case, flags, steps, original)


from .rag import FINAL_MAP  # noqa: E402  (tokenize() normalises final letters, so the stopwords must match that form)

STOPWORDS = {w.translate(FINAL_MAP) for w in
             ("אם", "יש", "מה", "של", "את", "על", "לא", "או", "גם", "זה", "אני", "הוא", "היא", "עם", "כל", "איך", "האם", "לי")}


def _question_hits_missing_sentence(question: str, quotes: list[dict]) -> bool:
    q_tokens = {t for t in tokenize(question, expand_query=True) if len(t) >= 2 and t not in STOPWORDS}
    for p in quotes:
        for sentence in re.split(r"[.;\n]", p["text"]):
            if any(m in sentence for m in MISSING_MARKERS):
                overlap = q_tokens & set(tokenize(sentence))
                if len(overlap) >= 2:
                    return True
    return False


def _result(question, action, answer, sources, retrieved, tool_calls, case, flags, steps, original=None) -> dict:
    return {
        "mode": "offline_workflow",
        "response_kind": "templated",
        "response_label_he": LABEL_HE,
        "question": original or question,
        "action": action,
        "answer_he": answer,
        "note": "templated reply from retrieved quotes and MCP results; no model call",
        "sources": sources,
        "retrieved": retrieved,
        "live_hint": needs_live_status(question),
        "tool_calls": tool_calls,
        "case": case,
        "flags": flags,
        "steps": steps,
        "usage": {"input_tokens": 0, "output_tokens": 0},
        "model": None,
        "raw_model_output": "",
        "demo": True,
    }
